{% set name = "dsnparse" %}
{% set version = "0.1.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d754c04c02bb838d9015d881e18060070dc64e1d903b0a8954fe6faea62f6dff

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - dsnparse

about:
  home: http://github.com/Jaymon/dsnparse
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: parse dsn urls

extra:
  recipe-maintainers:
    - Juanlu001
