{% set name = "dsnparse" %}
{% set version = "0.1.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ac5705b17cb28e8b115053c2d51cf3321dc2041b1d75e2db6157e05146d0fba

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - dsnparse
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Jaymon/dsnparse
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Parse dsn urls.
  description: Parse dsn urls.
  doc_url: https://github.com/Jaymon/dsnparse
  dev_url: https://github.com/Jaymon/dsnparse

extra:
  recipe-maintainers:
    - Juanlu001
