travis:
  secure:
    BINSTAR_TOKEN: DbTl2WYSsuUIKiEfMnNqpUNuC2hD8YPvb4TpXMIKClRtEXXK+FgPtz6hnehEEDvVeBTbha8PUD96jWtDV5SSYucdwzOfs8StmjOISSNOWFjiTI1k+7xSmVfeDJFu81b6bEIIEPXSeTNZLvCzkaVF1+XMI7ZkTX1VKQh0uOsuTsng6GnBDEeAMsVYpKVFLxvZHht3EAj4eMyUNW+cLwjZJI9/9dDzPSrCaT6ABasVUl6k4PxMmo1GzvXzzFJ4vqDerNGwYHOk6HH/9NJTTpNhVYeyTBfYySyCxZIljGr8Z9c5VyXB+fW7LW0ES9YcEvn1HkVVx1Ln4Ha/lNnpfYM53MQGBXwmmFDwF7Wpt56NX89YwaSW+NYqwUKUkEDqtjfg/5I5kPPRG+LxXsRvKNVrY8QoTlNqKaqtZFeAz0+qrDyB7IujNMquO/v+LIxuhx0pmmlqbXIk+JsGWjWPNGszuC/hVB3lSHshYT+CzTldS5YsZPcTA6+DbNVXeQCKwug8Kkj68TkkyNuKLjRHsqmeBwvhZvJYP8ncVV1LiXTe8ImK2iAvJTCeBH4Xlx9jSSqCCu2cRzzjLLVVAYgubP5LI4dMI7vNL5hs3ofSbjXLmWtqBxmOfZvbb5O7T0QlAuFo6upMNntd8w5sWqM8i4nlKNP3rq59HH8+Vs4dIwbyA+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
